<h2>Project 0: Julia Basics</h2>

<h3>Introduction</h3>

<p>In this project, you will write a function to compute Euclidean distances between sets of vectors, and get familiar with the Vocareum system that we will be using this semester. </p>

<strong>How to submit:</strong> You can submit your code using the red <strong>Submit</strong> button above. This button will send any code below surrounded by <strong>#&lt;GRADED&gt;</strong><strong>#&lt;/GRADED&gt;</strong> tags below to the autograder, which will then run several tests over your code. By clicking on the <strong>Details</strong> dropdown next to the Submit button, you will be able to view your submission report once the autograder has completed running. This submission report contains a summary of the tests you have failed or passed, as well as a log of any errors generated by your code when we ran it.

Note that this may take a while depending on how long your code takes to run! Once your code is submitted you may navigate away from the page as you desire -- the most recent submission report will always be available from the Details menu.

<p><strong>Evaluation:</strong> Your code will be autograded for technical
correctness and--on some assignments--speed. Please <em>do not</em> change the names of any provided functions or classes within the code, or you will wreak havoc on the autograder. Furthermore, <em>any code not surrounded by <strong>#&lt;GRADED&gt;</strong><strong>#&lt;/GRADED&gt;</strong> tags will not be run by the autograder</em>. However, the correctness of your implementation -- not the autograder's output -- will be the final judge of your score.  If necessary, we will review and grade assignments individually to ensure that you receive due credit for your work.

<p><strong>Academic Integrity:</strong> We will be checking your code against other submissions in the class for logical redundancy. If you copy someone else's code and submit it with minor changes, we will know. These cheat detectors are quite hard to fool, so please don't try. We trust you all to submit your own work only; <em>please</em> don't let us down. If you do, we will pursue the strongest consequences available to us.

<p><strong>Getting Help:</strong> You are not alone!  If you find yourself stuck  on something, contact the course staff for help.  Office hours, section, and the <a href="https://piazza.com/class/icxgflcnpra3ko">Piazza</a> are there for your support; please use them.  If you can't make our office hours, let us know and we will schedule more.  We want these projects to be rewarding and instructional, not frustrating and demoralizing.  But, we don't know when or how to help unless you ask.  



# Numpy
In this and future projects should you choose you use python, you will make a great deal of use of the numpy package. Numpy is a package that contains many routines for fast matrix and vector operations. Behind the scenes, rather than executing slow Python code, numpy functions often execute code that is compiled and highly optimized.

If you are not familiar with the Numpy package, you can read an overview of it <a href="https://docs.scipy.org/doc/numpy-dev/user/quickstart.html">here</a>, and find a full API <a href="https://docs.scipy.org/doc/numpy/reference/">here</a>. We import numpy for you below.

In [1]:
#<GRADED>
import numpy as np # Numpy is Python's built in library for matrix operations.
                   # We will be using it a lot in this class!
#</GRADED>


<h3> Euclidean distances in Python </h3>

<p>Many machine learning algorithms access their input data primarily through pairwise distances. It is therefore important that we have a fast function that computes pairwise (Euclidean) distances of input vectors. Assume we have $n$ data vectors $\vec x_1,\dots,\vec x_n\in{\cal R}^d$ and $m$ vectors $\vec z_1,\dots,z_m\in{\cal R}^d$. And let us define two matrices $X=[\vec x_1,\dots,\vec x_n]\in{\cal R}^{d\times n}$, where the $i^{th}$ column is a vector $\vec x_i$ and similarly $Z=[\vec z_1,\dots,\vec z_m]$. Our distance function takes as input the two matrices $X$ and $Z$ and outputs a matrix $D\in{\cal R}^{n\times m}$, where 
	$$D_{ij}=\sqrt{(\vec x_i-\vec z_j)^\top (\vec x_i-\vec z_j)}.$$
</p>

A naïve implementation to compute pairwise distances may look like the code below:

In [2]:
def l2distanceSlow(X,Z=None):
    if Z is None:
        Z = X
    
    n,d = X.shape     # dimension of X
    m= Z.shape[0]     # dimension of Z
    D=np.zeros((n,m)) # allocate memory for the output matrix
    for i in range(n):     # loop over vectors in X
        for j in range(m): # loop over vectors in Z
            D[i,j]=0.0; 
            for k in range(d): # loop over dimensions
                D[i,j]=D[i,j]+(X[i,k]-Z[j,k])**2; # compute l2-distance between the ith and jth vector
            D[i,j]=np.sqrt(D[i,j]); # take square root
    return D

Please read through the code carefully and make sure you understand it. It is perfectly correct and will produce the correct result ... eventually. To see what is wrong, try running the l2distanceSlow code on an extremely small matrix X:


In [83]:
X=np.random.rand(700,100)
print("Running the naive version for the first time ...")
%time D=l2distanceSlow(X)

Running the naive version for the first time ...
CPU times: user 41 s, sys: 0 ns, total: 41 s
Wall time: 41 s


In [102]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
B=np.matrix([[11,12,13],[14,15,16]])
print(l2distanceSlow(A,B))
print(l2distance(A,B))


print(l2distanceSlow(A))
print(l2distance(A))

[[ 17.32050808  22.5166605 ]
 [ 12.12435565  17.32050808]
 [  6.92820323  12.12435565]]
[[ 17.32050808  22.5166605 ]
 [ 12.12435565  17.32050808]
 [  6.92820323  12.12435565]]
[[  0.           5.19615242  10.39230485]
 [  5.19615242   0.           5.19615242]
 [ 10.39230485   5.19615242   0.        ]]
[[  0.           5.19615242  10.39230485]
 [  5.19615242   0.           5.19615242]
 [ 10.39230485   5.19615242   0.        ]]


In [89]:
P=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
Q=np.matrix([[10,11,12],[13,14,15]])
maxNum=max(P.shape[0],Q.shape[0])

Z3=np.zeros((maxNum,maxNum))
# if P.shape[0]!=maxNum:
    
Z3[:P.shape[0],:P.shape[1]]=P
print(Z3)
    
if Q.shape[0]!=maxNum:
    Z2=np.zeros((maxNum,maxNum))
    #print(Z1[:Q.shape[0],:Q.shape[1]])
    #print(Z1)
    Z2[:Q.shape[0],:Q.shape[1]]=Q   

print(Z2)

D1=l2distanceSlow(P,Q)
print(D1)
print(P.ndim)

print()
print(Z3)
print(Z2)
D2=innerproduct(Z3)+innerproduct(Z2)-innerproduct(Z3,Z2)-innerproduct(Z2,Z3)
print(D2)
print(np.sqrt(abs(D2)))


D2=innerproduct(Z3)+innerproduct(Z2)-2*innerproduct(Z3,Z2)
print(D2)
print(np.sqrt(abs(D2)))

#D2=l2distance(P,Q)
#print(D2)

# A=np.matrix([[1,2,3]])
# B=np.matrix([[10,11,12]])
# print(innerproduct(A,B))
# print (innerproduct(B,A))
# print (innerproduct(A))
# print(innerproduct(Q.resize(3,3)))
# print(P.dtype)
#print(innerproduct(P).sum(2))


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[ 10.  11.  12.]
 [ 13.  14.  15.]
 [  0.   0.   0.]]
[[ 15.58845727  20.78460969]
 [ 10.39230485  15.58845727]
 [  5.19615242  10.39230485]]
2

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[ 10.  11.  12.]
 [ 13.  14.  15.]
 [  0.   0.   0.]]
[[ 243.  243. -216.]
 [ 243.  243. -216.]
 [-216. -216.  194.]]
[[ 15.58845727  15.58845727  14.69693846]
 [ 15.58845727  15.58845727  14.69693846]
 [ 14.69693846  14.69693846  13.92838828]]
[[ 243.  324.   50.]
 [ 162.  243.  122.]
 [-482. -554.  194.]]
[[ 15.58845727  18.           7.07106781]
 [ 12.72792206  15.58845727  11.04536102]
 [ 21.9544984   23.53720459  13.92838828]]


In [77]:
A=[[1,2,3],[4,5,6]]
B=[[1,2,3],[4,5,6]]
# print(np.einsum('ij,ij',A,B))
# print(np.einsum('ij->i',A,B))



print(np.einsum('ij,ij->ij',A,B))
print(np.einsum('ij,ij->i',A,B))

S=np.tile(np.einsum('ij,ij->i',A,B),3).reshape((3,2
                     )).T
print(S)

P=np.matrix([[11,12,13],[14,15,16]])

print(P.T)
R=np.tile(np.einsum('ij,ij->j',P.T,P.T),3).reshape(3,2)
# R=np.tile(np.einsum('ij,ij->j',P,P),3).reshape((3,2))
print(R)






[[ 1  4  9]
 [16 25 36]]
[14 77]
[[14 14 14]
 [77 77 77]]
[[11 14]
 [12 15]
 [13 16]]
[[434 677]
 [434 677]
 [434 677]]


This code defines some random data in $X$ and computes the corresponding distance matrix $D$. The <em>%time</em> statements time how long this takes. When I ran the code, the <em>l2distanceSlow</em> function took <strong>43.6s to run</strong>! 

This is an appallingly large amount of time for such a simple operation on a small amount of data, and writing code like this to deal with matrices in this class will result in code that takes <strong>days</strong> to run. 


<strong>As a general rule, you should avoid tight loops at all cost.</strong> As we will see in the remainder of this assignment, we can do much better by performing bulk matrix operations using the <em>numpy</em> package, which calls highly optimized compiled code behind the scenes.





<h4> How to program in Julia / Matlab / Numpy </h4>

<p>Although there is an execution overhead per line in Python, matrix operations are extremely optimized and very fast. In order to successfully program in this course, you need to free yourself from "for-loop" thinking and start thinking in terms of matrix operations. Python for scientific computing can be very fast if almost all the time is spent in a few heavy duty matrix operations. In this assignment you will do this, and transform the function above into a few matrix operations <em>without any loops at all.</em> </p> 

<p>The key to efficient programming in Python for machine learning in general is to think about it in terms of mathematics, and not in terms of Loops. </p>

<p>	(a) Show that the Gram matrix (aka inner-product matrix)
$$	G_{ij}=\vec x_i^\top\vec z_j $$
can be expressed in terms of a pure matrix multiplication. Once you are done with the derivation, implement the function <strong><code>innerproduct</code></strong>.</p>


In [3]:
#<GRADED>
def innerproduct(X,Z=None):
    # function innerproduct(X,Z)
    #
    # Computes the inner-product matrix.
    # Syntax:
    # D=innerproduct(X,Z)
    # Input:
    # X: nxd data matrix with n vectors (rows) of dimensionality d
    # Z: mxd data matrix with m vectors (rows) of dimensionality d
    #
    # Output:
    # Matrix G of size nxm
    # G[i,j] is the inner-product between vectors X[i,:] and Z[j,:]
    #
    # call with only one input:
    # innerproduct(X)=innerproduct(X,X)
    #
    if Z is None: # case when there is only one input (X)
        G=np.matmul(X,X.transpose())
    else:  # case when there are two inputs (X,Z)
        G=np.matmul(X,Z.transpose())
    
    return G
#</GRADED>


If your code is correct you should pass the following two tests below. 

In [85]:
# a simple test for the innerproduct function
M=np.array([[1,2,3],[4,5,6],[7,8,9]])
Q=np.array([[11,12,13],[14,15,16]])
print(np.linalg.norm(innerproduct(M,M)-innerproduct(M))<1e-16) # test1: Inner product with itself
print(np.all(innerproduct(M,Q).T==np.array([[74,182,290],[92,227,362]])))

True
True


(b) Let us define two new matrices $S,R\in{\cal R}^{n\times m}$ 
		$$S_{ij}=\vec x_i^\top\vec x_i, \ \ R_{ij}=\vec z_j^\top\vec z_j.$$
 	Show that the <em>squared</em>-euclidean matrix $D^2\in{\cal R}^{n\times m}$, defined as
		$$D^2_{ij}=(\vec x_i-\vec z_j)^2,$$
	can be expressed as a linear combination of the matrix $S, G, R$. (Hint: It might help to first express $D^2_{ij}$ in terms of inner-products.) What do you need to do to obtain the true Euclidean distance matrix $D$?</p></td>
	
<p>

<p>	(c) Implement the function <strong><code>l2distance</code></strong>, which computes the Euclidean distance matrix $D$ without a single loop:

In [4]:
#<GRADED>
def l2distance(X,Z=None):
    # function D=l2distance(X,Z)
    #
    # Computes the Euclidean distance matrix.
    # Syntax:
    # D=l2distance(X,Z)
    # Input:
    # X: nxd data matrix with n vectors (rows) of dimensionality d
    # Z: mxd data matrix with m vectors (rows) of dimensionality d
    #
    # Output:
    # Matrix D of size nxm
    # D(i,j) is the Euclidean distance of X(i,:) and Z(j,:)
    #
    # call with only one input:
    # l2distance(X)=l2distance(X,X)
    #

    if Z is None:
#          D=innerproduct(X)+innerproduct(Z)-innerproduct(X,Z)-innerproduct(Z,X)
        m=n=X.shape[0]
        d=X.shape[1]
#         m=X.shape[0]
        
        S=np.tile(np.einsum('ij,ij->i',X,X),m).reshape((m,n)).T
        R=np.tile(np.einsum('ij,ij->j',X.T,X.T),n).reshape(n,m)
        G=2*innerproduct(X,X)
        D=S+R-G
    else:  # case when there are two inputs (X,Z)
#         D=innerproduct(X)+innerproduct(Z)-innerproduct(X,Z)-innerproduct(Z,X)
        n=X.shape[0]
        d=X.shape[1]
        m=Z.shape[0]
        
        S=np.tile(np.einsum('ij,ij->i',X,X),m).reshape((m,n)).T
        R=np.tile(np.einsum('ij,ij->j',Z.T,Z.T),n).reshape(n,m)
        G=2*innerproduct(X,Z)
        D=S+R-G
                 
        
        
    return np.sqrt(np.absolute(D))
#</GRADED>

Test your l2-distance function again:

In [5]:
import time
current_time = lambda: int(round(time.time() * 1000))

X=np.random.rand(700,100)
Z=np.random.rand(300,100)

print("Running the naive version ...")
before = current_time()
D=l2distanceSlow(X)
after = current_time()
t_slow = after - before

print("Running the vectorized version ...")
before = current_time()
D=l2distance(X)
after = current_time()
t_fast = after - before

speedup = t_slow / t_fast
print("The numpy code was {} times faster!".format(speedup))

Running the naive version ...
Running the vectorized version ...
The numpy code was 2477.6111111111113 times faster!


How much faster is your code now? With this implementation you should easily be able to compute the distances between <strong>many more</strong> vectors. You can easily see how, even for small datasets, the for-loop based implementation could take several days or even weeks to perform basic operations that take seconds or minutes with well-written numpy code.